### ISSUE TITLE
[Request] Allow Fullscreening

### ISSUE THREAD

**Issue by twiclo** [bhamrick/multitwitch#26]
The fullscreen button seems to be greyed out. If it's possible that should be undone so I can fullscreen a specific stream if there's something I want to focus on going on there.

**Comment by bhamrick** [comment]
Hi, I believe this is a bug in Twitch's embedded video player due to the URL similarity. I had a similar issue a few years ago with autoplay. You can work around it by using www.multitwitch.tv instead of multitwitch.tv (it's the same page, but the different URL gets around whatever is disabling full screen).

**Comment by twiclo** [comment]
If that really is the workaround then please set the web server to force the www
