### ISSUE TITLE
/<stream> URLs being eaten by GoDaddy URL shortener service

### ISSUE THREAD

**Issue by pollysee** [bhamrick/multitwitch#33]
This is probably something to do with GoDaddy, and not the site. But currently, trying to enter more than one stream name into the URL will redirect the user to some kind of GoDaddy URL shortener page with an error.

**Comment by bhamrick** [comment]
Hi, thanks for the report! I've verified the issue and am looking into what I can do to work around it. For now, you can get the proper behavior by using www.multitwitch.tv in the url instead of just multitwitch.tv

**Comment by bhamrick** [comment]
This should be fixed, although the DNS changes may take a little bit to propagate. I'm going to go ahead and close this issue but please feel free to open a new one if you continue to have problems.

For the curious, this happened because GoDaddy doesn't allow for CNAME records at the root, so I was using their domain forwarding, but they apparently recently made a change that made the forwarding fail on subpages as you noticed. I took this opportunity to move off of Heroku, something I had been thinking of doing for a while now, and that allows me to use an A record instead of a CNAME which avoids using their domain forwarding.
